services:
  - type: web
    name: olive
    env: php
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      composer install --no-interaction --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-dev
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force --no-interaction
    startCommand: npm run start
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://olive.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
